### PR TITLE
Merge NNbar annihilation detailed balance test

### PR DESCRIPTION
**Pull request by stdnmr**
I added some NNbar annihilation tests that should be included to test and plot this functionality in SMASH.

Branch is not fully mergeable at the moment, but should not be difficult to rebase on current main.

### CODE REVIEW

**Comment by stdnmr** [comment]
Rebased on master and as NNbar is now in SMASH-2.2 ready for review and merge. Had some weird multi-tasking issue when running the analysis, so @NGoetz could you try once to run the two new targets. Would probably anyway good as part of the review.

**Comment by NGoetz** [comment]
I started the `detailed_balance_multi_N_Nbar_5pi_sims` target but with SMASH-2.2.1 I got the error 
`[13'18'09] FATAL         Main        : SMASH failed with the following error:
                                       Only use maximum cross section with the geometric collision criterion. Use Fixed_Min_Cell_Length to change the grid size for the stochastic criterion.
`

**Comment by stdnmr** [comment]
Sorry, about that. Fixed now. Forgot to update the config for the 5-to-2 target.

**Comment by stdnmr** [comment]
Yes, the warnings are ok. As the runs finish the sampling is not hanging, just inefficent in cases, but that is due to the high 5-body phase space.

**Pull request merged**
