### PR TITLE
Add support for binary output version 7

### LINKED ISSUE #12: Update reader script for format version 7
Getting this error reading newest SMASH output:
`Fatal error: unknown format version =  7`

### PR DESCRIPTION
**Pull request by vks**
Fixes #12.

### CODE REVIEW

**Comment by doliinychenko** [comment]
This looks good, please merge it (the sooner the better). Unfortunately, I don't have rights to approve it formally in git.

**Comment by vks** [comment]
I'm afraid I have as many rights as you, so I can't merge it either. @stdnmr @akschaefer @elfnerhannah Could you please merge it and consider giving the SMASH developers more rights?

**Comment by stdnmr** [comment]
In general, our policy is that only members who work on the projects get write access. This also means that they may have to ask once at the beginning to get them. Since @doliinychenko and @vks clearly are working on the project, I fixed your rights to include write access.

Do you think this policy should be changed, @vks?

/cc @elfnerhannah 

I am also merging the PR.

**Comment by elfnerhannah** [comment]
I think the policy is fine and works well so far. We have only very few occasions where neither @stdnmr or myself are there to change settings.

**Comment by vks** [comment]
I agree this policy makes sense.

**Pull request merged**
