### PR TITLE
Inghirami/improve read binary output

### PR DESCRIPTION
**Pull request by gabriele-inghirami**
With this modification the script _read_binary_output.py_ accepts a block only if it is able to retrieve a recognizable label for the next one, thus improving the reliability of data in the case of a premature ending of SMASH (at the price of a tiny larger execution time).

https://theory.gsi.de/~ginghir/tmp_test_data/data_for_testing.zip provides an example in which this modification might be useful.
The data refer to a SMASH-2.1 run manually aborted before its natural end.
If one tries to work with the data using ` ipython` with something like (the path will be different, of course):
```
In [1]: from read_binary_output import *                                                         
In [2]: with BinaryReader("/home/g/data_for_testing/particles_binary.bin.unfinished") as reader: 
   ...:   smash_version = reader.smash_version 
   ...:   for b in reader: 
   ...:       print(b['type']) 
   ...:       if(b['type']=='p'): 
   ...:           print(str(get_block_px(b))) 
   ...:   
   ```
with the current version one gets (I report only the final lines):
```
p
-4.440892098500626e-15
p
-1.1157297308272973e-11
p
-1.1161738200371474e-11
p
0.742975483157231
```
while, with the modified version:
```
p
-4.440892098500626e-15
p
-1.1157297308272973e-11
p
-1.1161738200371474e-11
```
i.e. the final incomplete block with corrupted double values is discarded.

The proposed changes are conceptually very simple, however, since the script deals with many different versions of the binary format that have not been tested after the modification, I recommend the reviewer(s) to carefully check for possible undetected typos.
Since this topic has been discussed also in https://github.com/smash-transport/smash-analysis/pull/45 , I mention here @akschaefer @doliinychenko @AxelKrypton @stdnmr .

### CODE REVIEW

**Review by NGoetz — APPROVED** [review]
I have tested the code with the given example file and with some manually created test cases, and it seems to work as expected. However, as I am not an expert on the binary file format, I would recommend to wait for a second review.

**Comment by akschaefer** [comment]
I can only take care of a second review the earliest next week, sorry!

**Comment by akschaefer** [comment]
The code changes look good. I also approve. As a last check and to make sure we don't break something, @NGoetz will try actual analysis suite runs and if they are successful, it can be merged.

**Comment by NGoetz** [comment]
There is indeed some problem when testing with analysis suite runs, but my lack of knowledge about the binary output makes it a bit troublesome to pin them down.
I tested the elastic_box target (scatrate vs N only), using this branch of analysis and the current smash-devel master. The [output file](https://github.com/smash-transport/smash-analysis/files/8233218/0.zip) is read using /test/elastic_box/elastic_scatrate.py, which calles the binary reader. The error message is

> File "/home/goetz/Desktop/smash-analysis/test/elastic_box/elastic_scatrate.py", line 61, in <module>
>     res = count_elastic_scat(coll_file, t_start)
>   File "/home/goetz/Desktop/smash-analysis/test/elastic_box/elastic_scatrate.py", line 25, in count_elastic_scat
>     'ev_num' : event_num,
> UnboundLocalError: local variable 'event_num' referenced before assignment

There seem to be multiple issues appearing in the binary reader. First of all, somehow this file has the wrong magic number, but even when this check is skipped, _read_binary_block_v7 does not produce an output because it detects a p block with a tmp_type i.

I checked that this issue is only present on this branch. The smash-analysis master works normally.

**Comment by gabriele-inghirami** [comment]
Thank you for reporting. I will give it a look asap (probably tomorrow).

**Comment by gabriele-inghirami** [comment]
Hopefully now it should be fixed.
Can you, please, check, again?

**Comment by NGoetz** [comment]
Yes, all is working fine now, thank you! This PR is ready to go.

**Pull request merged**
