### PR TITLE
Inghirami/update to python3

### PR DESCRIPTION
**Pull request by gabriele-inghirami**
With this PR we update the scripts to Python 3.8. However, due to the long time needed to perform the full analysis, these modifications have been tested (with SMASH-2.0.2) only once, using a reduced set of events and often restarting from the position of the last error. I checked only that the tests ended without error, not the full set of plots and the final report has not been generated. Therefore, even if I am not expecting a complete mess, here and there we might need to fix some problems not detected during the upgrade, hopefully not severe. Probably, the best approach is to try repeat the analysis done for SMASH 2.1 and repair what is not yet working properly.

### CODE REVIEW

**Comment by akschaefer** [comment]
I can take a look at the diff and do the review there. @NGoetz, since you already set up the entire analysis framework for the new tag. Could you please run the full glory once on the python3 branch (and produce the webpage) so we can check that nothing is broken?

**Comment by elfnerhannah** [comment]
My suggestion is to run the analysis for the actual tag, which we will do soon, with the new Python 3 scripts.

**Comment by NGoetz** [comment]
Okay I will run for the actual tag both analysis suites and then report the results.

**Comment by elfnerhannah** [comment]
> Okay I will run for the actual tag both analysis suites and then report the results.

For the sake of computing hours used, I would suggest to only run the new Python 3 and only if things look strange, run the old setting again.

**Comment by gabriele-inghirami** [comment]
As a short preliminary comment, I had the bad idea to include the simple changes of recent commit in master in my branch before pushing the recent changes. The idea was to save some time to the reviewer before the merge, but I realized that it does more harm than good...

**Comment by gabriele-inghirami** [comment]
Then, a comment about the most recent recent bug fix, on which I worked during the _sprint_ session.
Before the fix, the analysis stopped when running this piece of code in _test/cross_sections/plot.py_:
```
sorted_sigma_table = {}
for name, sigma in sigma_table.items():
     if name.endswith('_err'):
          # We skip errors
           continue
     error = sigma_table[name + '_err']
     sorted_sigma_table[name] = (sigma, error, sigma.sum() / total_sigma)
```
with an error message like:
```
Scanning dependencies of target cross_sections_plots
[  0%] Combining results for Analyzing data for cross_sections/piplus_piminus (individual).
[  0%] Plotting data (individual) for cross_sections/piplus_piminus.
[  0%] Combining results for Analyzing data for cross_sections/piplus_piminus (grouped).
[  0%] Plotting data (grouped) for cross_sections/piplus_piminus.
[  0%] Combining results for Analyzing data for cross_sections/piplus_piminus (final grouped).
[  0%] Plotting data (final grouped) for cross_sections/piplus_piminus.
[  0%] Combining results for Analyzing data for cross_sections/piplus_piminus (process type).
[  0%] Plotting data (process type) for cross_sections/piplus_piminus.
[  0%] Combining results for Analyzing data for cross_sections/piminus_proton (final individual for resonance).
[  0%] Combining results for Analyzing data for cross_sections/piminus_proton (final individual).
[  0%] Plotting data (lambda_X) for cross_sections/piminus_proton.
Traceback (most recent call last):
  File "/lustre/hyihp/ginghir/smash-analysis-current/smash-analysis-wb/test/cross_sections/plot.py", line 245, in <module>
    for name, sigma in sigma_table.items():
RuntimeError: dictionary changed size during iteration
make[3]: *** [test/cross_sections/CMakeFiles/cross_sections_plots.dir/build.make:174: test/cross_sections/piminus_proton/xs_lambda_X.pdf] Error 1
```
(the line number in the current code on GitHub might be different)
However, _sigma_table_ is accessed only to read data, nothing is written there. Moreover, this part of the code is executed several times with other cross sections without getting an error. I checked the dictionary, but its content did not reveal any major issues. 
In the old python2 code _sigma_table_ was defined as:
`sigma_table = OrderedDefaultDict(lambda: np.zeros(len(sqrts)))`
while now is defined as:
`sigma_table = defaultdict(lambda: np.zeros(len(sqrts)))`

At some point the error disappeared when printing the contents of _sigma_table_ to inspect them. That might also be the reason why, when I hit this error some time ago, I attributed it just to a statistical issue (there are some if one does not run enough events, e.g. there is an assert and another check later if some quantities are 0), but I did not realize that this was just due to my prints and, once commented, the error came back.

Right now the error seems to be fixed by adding, before iterating on _sigma_table_:
```
tmp_variable=sigma_table['total_err'].view()
del tmp_variable
```
which should have a minimal impact on the performance. Basically I explicitly access the element of the array that creates problems by using a view on a temporary variable that it is then destroyed.

I have a hypothesis about what could be the root of the error: essentially, something that goes wrong with a previous assignment, that it is not really done for some reason, e.g. for optimization reasons because there is a zero quantity and the default lambda function, which creates an array of zeroes, waits to do its job and does not create this element, as well, until it is accessed in the iteration, even if only in read mode. At this point, the lambda function wakes up and adds another entry in the dictionary or, alternatively, an assignment is actually done in delay, but this changes the size of the dictionary during the iteration and it produces an error. 
The fix simply forces whoever is in charge to fill the entry in the dictionary to do it before the iteration because something (view()) wants to use it. 

I might be wrong and certainly I am not a Python guru, but, unless there is a caveat that I did not get in using defaultdictionaries, I have the impression that this should not happen and there is a bug somewhere in the Python version included in the container. If this is the case, maybe in the future this error could disappear and the fix become unnecessary (but anyway, it is neutral and its impact is negligible, so if somebody forgets to remove it that's not a problem).

Do you have comments, hints or suggestions? (@NGoetz , @vks, @akschaefer , @stdnmr , @AxelKrypton )

**Comment by AxelKrypton** [comment]
I am not a python guru at all, I was just reading your comment and this remembered me that `python3` changed what methods like `keys()` and `items()` returned and in particular in the new approach they return a [`vewobject`](https://docs.python.org/3/library/stdtypes.html#dict-views). Now, this is not really the problem here, but it is somehow connected to the abstract idea. Since `sigma_table` is a `defaultdict`, 
> when each key is encountered for the first time, an entry is automatically created using the `default_factory` function which returns an empty `list`, [...] [read here :book:](https://docs.python.org/release/2.5.2/lib/defaultdict-examples.html)

hence if the key doesn't already exist a default value is retrieved (hence the name) and the key is added to the dictionary (with the default value). My very naive guess is that `sigma_table[name + '_err']` could be the culprit, since it might change the dictionary (if the element is not there), although it looks as a harmless reading operation. In C++ this is the sneaky behaviour of e.g. a `std::map`. And this also explain why printing `sigma_table` (I guess before the look) was making the problem disappear, since the accessed items were created and the dictionary was not changed later in the loop.

Now, I do not know what you need here, but using a `defaultdict` is a pattern where it is important to know what happens. There is a [`get(key, default=None)` method](https://docs.python.org/3/library/stdtypes.html?highlight=get#dict.get) to
> Return the value for key if key is in the dictionary, else default. If default is not given, it defaults to None, so that this method never raises a KeyError

so it might be used to safely inspect a `defaultdict` in a loop.

Does this make sense to you? :thinking:

**Comment by gabriele-inghirami** [comment]
> My very naive guess is that sigma_table[name + '_err'] could be the culprit, since it might change the dictionary (if the element is not there), although it looks as a harmless reading operation

Yes, this is also what I think. For some reasons the entry "total_err" it is not yet created when we enter into the loop, so it is created when accessed the first time in that point and that changes the dictionary. But, in principle, it should have been already created in the assignment:
`sigma_table[colnames[i + 1]] = columns[i + 1]  # error`
columns is obtained from a `numpy.loadtxt` call and, in columns, the key `total_err` exists...

However, I don't plan to dig further into this issue, which seems to be related, if not to a bug, to a nuisance of Python...
Unless, of course, the test still does not work as expected (now it should end without errors, but I did not look at the plots).

Thank you for the comment! (@AxelKrypton )

**Review by NGoetz — APPROVED** [review]
All changes look good to me. The branch has been tested for the latest release candidate and works fine.

**Pull request merged**
